name: Run Flutter Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Get dependencies
        run: flutter pub get
      - name: Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run unit tests
        run: flutter test
