name: Flutter tests
on:
  pull_request:
    branches:
      - main

jobs:
  analyze_and_fix:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código do repositório
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # Configura o SDK Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.1" # Especifique a versão do Flutter aqui. Remova essa linha se quiser a versão estável mais recente.

      # Instala as dependências do Flutter
      - name: Install dependencies
        run: flutter pub get

      - name: Build Runner Files Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - run: flutter test
